name: Bug Report
description: Report a bug in Pindrop
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!

        ## System Information

        **Please copy your system info from Pindrop:**
        1. Open Pindrop
        2. Go to **Settings → About**
        3. Click **"Copy System Info for Bug Report"**
        4. Paste it in the field below

  - type: textarea
    id: system-info
    attributes:
      label: System Information
      description: Paste the output from Settings → About → "Copy System Info for Bug Report"
      placeholder: |
        Pindrop: 1.1.0 (42)
        macOS: Version 15.1 (Build 24B83)
        Chip: Apple Silicon
        Model: openai_whisper-small
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please describe the bug in detail.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please copy and paste any relevant log output (if available). You can check Console.app for Pindrop logs.
      render: shell

  - type: checkboxes
    id: permissions
    attributes:
      label: Permissions
      description: Which permissions have you granted to Pindrop?
      options:
        - label: Microphone access
        - label: Accessibility access
