name: Feature Request
description: Suggest a new feature for Pindrop
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe it below.

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear description of what the problem is.
      placeholder: I'm frustrated when...

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: Any alternative solutions or features you've considered.

  - type: dropdown
    id: scope
    attributes:
      label: Feature Scope
      description: How would you categorize this feature?
      options:
        - Core functionality (transcription, recording)
        - User interface (UI/UX improvement)
        - Settings/configuration
        - Integration (with other apps/services)
        - Performance optimization
        - Documentation
        - Other

  - type: dropdown
    id: priority
    attributes:
      label: How important is this feature to you?
      description: This helps us prioritize features.
      options:
        - Critical - I can't use Pindrop without it
        - High - Would significantly improve my workflow
        - Medium - Nice to have
        - Low - Just an idea

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context, screenshots, or mockups about the feature request.

  - type: checkboxes
    id: contribute
    attributes:
      label: Contribution
      description: Would you be interested in contributing this feature?
      options:
        - label: I'd like to work on this feature myself
