//
//  SharedLocalization.kt
//  Pindrop
//
//  Created on 2026-03-29.
//
//  AUTO-GENERATED by convert_xcstrings_to_kmp.py — do not edit manually.
//

package tech.watzon.pindrop.shared.uilocalization

/**
 * Shared localization authority.
 *
 * Provides runtime string lookup by xcstrings key and locale.
 * All strings are loaded from the bundled strings_bundle.json resource.
 * Swift calls [getString] to resolve localized text at runtime.
 */
object SharedLocalization {

    /**
     * Mapping from xcstrings keys to KMP resource identifiers.
     * Populated from key_mapping.json by the conversion script.
     */
    internal var _keyMapping: Map<String, String> = emptyMap()

    /**
     * All localized strings: locale → (kmpId → localized value).
     * Populated from strings_bundle.json by platform-specific loader.
     */
    private var _strings: Map<String, Map<String, String>> = emptyMap()

    /**
     * Whether the strings have been initialized.
     */
    private var _initialized: Boolean = false

    /**
     * Initialize with pre-loaded data.
     * Called by platform-specific code after loading JSON resources.
     */
    fun initialize(keyMapping: Map<String, String>, strings: Map<String, Map<String, String>>) {
        _keyMapping = keyMapping
        _strings = strings
        _initialized = true
    }

    /**
     * Returns all KMP resource string identifiers.
     */
    fun allKeys(): Set<String> {
        return _keyMapping.values.toSet()
    }

    /**
     * Check if a given KMP identifier exists.
     */
    fun hasKey(key: String): Boolean {
        return _keyMapping.values.contains(key)
    }

    /**
     * Returns the set of supported locale codes.
     */
    fun supportedLocales(): Set<String> {
        return setOf(
            "en", "de", "es", "fr", "it", "ja", "ko", "nl", "pt-BR", "tr", "zh-Hans"
        )
    }

    /**
     * Returns the mapping from xcstrings keys to KMP resource identifiers.
     */
    fun keyMapping(): Map<String, String> {
        return _keyMapping.toMap()
    }

    /**
     * Look up a KMP identifier from an xcstrings key.
     */
    fun kmpIdentifierForXcKey(xcKey: String): String? {
        return _keyMapping[xcKey]
    }

    /**
     * Look up an xcstrings key from a KMP identifier.
     */
    fun xcKeyForKmpIdentifier(kmpId: String): String? {
        return _keyMapping.entries.find { it.value == kmpId }?.key
    }

    /**
     * Resolve a localized string by its original xcstrings key and locale.
     *
     * This is the primary entry point for Swift consumers.
     * Falls back to English if the locale is not found,
     * then falls back to the key itself if no translation exists.
     */
    fun getString(xcKey: String, locale: String): String {
        val kmpId = _keyMapping[xcKey]
        if (kmpId != null) {
            return getStringById(kmpId, locale)
        }
        return xcKey
    }

    /**
     * Resolve a localized string by its KMP identifier and locale.
     */
    fun getStringById(kmpId: String, locale: String): String {
        if (!_initialized) return kmpId

        // Try exact locale match
        val localeStrings = _strings[locale]
        if (localeStrings != null) {
            val value = localeStrings[kmpId]
            if (value != null) return value
        }

        // Try language-only fallback (e.g., "pt" from "pt-BR")
        val langOnly = locale.split("-").firstOrNull()
        if (langOnly != null && langOnly != locale) {
            for ((locKey, locStrings) in _strings) {
                if (locKey.startsWith(langOnly)) {
                    val value = locStrings[kmpId]
                    if (value != null) return value
                }
            }
        }

        // Fall back to English
        val enStrings = _strings["en"]
        if (enStrings != null) {
            val value = enStrings[kmpId]
            if (value != null) return value
        }

        // Last resort: return the identifier
        return kmpId
    }
}
