//
//  SharedLocalization.kt
//  Pindrop
//
//  Created on 2026-03-29.
//
//  AUTO-GENERATED by convert_xcstrings_to_kmp.py — do not edit manually.
//

package tech.watzon.pindrop.shared.uilocalization

/**
 * Shared localization authority.
 *
 * Provides runtime string lookup by xcstrings key and locale.
 * All strings are embedded from Localizable.xcstrings via generated locale files.
 * Swift calls [getString] to resolve localized text at runtime.
 */
object SharedLocalization {

    /**
     * Mapping from xcstrings keys to KMP resource identifiers.
     * Generated from key_mapping.json by the conversion script.
     */
    internal val _keyMapping: Map<String, String> = KEY_MAPPING

    /**
     * Reverse mapping from KMP identifiers to xcstrings keys.
     */
    internal val _reverseMapping: Map<String, String> = _keyMapping.entries.associate { it.value to it.key }

    /**
     * All localized strings: locale → (kmpId → localized value).
     * Populated from per-locale generated files.
     */
    private val _strings: Map<String, Map<String, String>> = mapOf(
        "en" to STRINGS_EN,
        "de" to STRINGS_DE,
        "es" to STRINGS_ES,
        "fr" to STRINGS_FR,
        "it" to STRINGS_IT,
        "ja" to STRINGS_JA,
        "ko" to STRINGS_KO,
        "nl" to STRINGS_NL,
        "pt-BR" to STRINGS_PT_BR,
        "tr" to STRINGS_TR,
        "zh-Hans" to STRINGS_ZH_HANS,
    )

    /**
     * Returns all KMP resource string identifiers.
     */
    fun allKeys(): Set<String> {
        return _keyMapping.values.toSet()
    }

    /**
     * Check if a given KMP identifier exists.
     */
    fun hasKey(key: String): Boolean {
        return _keyMapping.values.contains(key)
    }

    /**
     * Returns the set of supported locale codes.
     */
    fun supportedLocales(): Set<String> {
        return _strings.keys.toSet()
    }

    /**
     * Returns the mapping from xcstrings keys to KMP resource identifiers.
     */
    fun keyMapping(): Map<String, String> {
        return _keyMapping.toMap()
    }

    /**
     * Look up a KMP identifier from an xcstrings key.
     */
    fun kmpIdentifierForXcKey(xcKey: String): String? {
        return _keyMapping[xcKey]
    }

    /**
     * Look up an xcstrings key from a KMP identifier.
     */
    fun xcKeyForKmpIdentifier(kmpId: String): String? {
        return _reverseMapping[kmpId]
    }

    /**
     * Resolve a localized string by its original xcstrings key and locale.
     *
     * This is the primary entry point for Swift consumers.
     * Falls back to English if the locale is not found,
     * then falls back to the key itself if no translation exists.
     */
    fun getString(xcKey: String, locale: String): String {
        val kmpId = _keyMapping[xcKey] ?: return xcKey
        return getStringById(kmpId, locale)
    }

    /**
     * Resolve a localized string by its KMP identifier and locale.
     */
    fun getStringById(kmpId: String, locale: String): String {
        // Try exact locale match
        val localeStrings = _strings[locale]
        if (localeStrings != null) {
            val value = localeStrings[kmpId]
            if (value != null) return value
        }

        // Try language-only fallback (e.g., "pt" from "pt-BR")
        val langOnly = locale.split("-").firstOrNull()
        if (langOnly != null && langOnly != locale) {
            for ((locKey, locStrings) in _strings) {
                if (locKey.startsWith(langOnly)) {
                    val value = locStrings[kmpId]
                    if (value != null) return value
                }
            }
        }

        // Fall back to English
        val enStrings = _strings["en"]
        if (enStrings != null) {
            val value = enStrings[kmpId]
            if (value != null) return value
        }

        // Last resort: return the key
        return kmpId
    }
}
